In [22]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import seaborn as sns
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split

In [23]:
def fit_model(x, b):
    n = len(x)
    x_bias = np.ones((n, 1))
    x = np.c_[x_bias, x]
    y_hat = x.dot(b)
    return y_hat


def find_betas(x, y):
    n = len(x)
    x_bias = np.ones((n, 1))
    x = np.c_[x_bias, x]
    betas = np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y)
    return betas


def predict(x, betas):
    n = len(x)
    x_bias = np.ones((n, 1))
    x = np.c_[x_bias, x]
    prediction = x.dot(betas)
    return prediction


def square_error(y, y_hat):
    error = y - y_hat
    square = error.T.dot(error)
    return square

def simple_gradeiant_descent1 (alpha,iters,x,y) :
    m = len(x)
    b0 = 0
    b1 = 0
    for i in range(iters):
        y_hat = b0 + x*b1
        b0 = b0 - alpha * 1/m * sum(y_hat - y)
        b1 = b1 - alpha * 1/m * sum((y_hat - y) * x)

    return b0 , b1

def gradeiant_descent (alpha,iters,x,y) :
    m = x.shape[0]
    k = x.shape[1]
    x_bais = np.ones((m,1))
    x = np.c_[x_bais,x]
    betas = np.random.randn(k+1,1)
    print(x.shape,y.shape,betas.shape)
    for i in range (iters):
        betas = betas - alpha * 2/m * x.T.dot(x.dot(betas)-y)
    return betas 

In [24]:
x = np.random.randn(100,5)
y = 15*x + 13 + 2*np.random.randn(100,5)
y = y[0:,0:1]
y.shape

(100, 1)

In [25]:
betas = gradeiant_descent(0.1,6000,x,y)
betas

(100, 6) (100, 1) (6, 1)


array([[13.27856821],
       [15.2764324 ],
       [ 0.09897232],
       [-0.26031363],
       [ 0.29543145],
       [ 0.13329286]])

In [26]:
betas = find_betas(x,y)
betas

array([[13.27856821],
       [15.2764324 ],
       [ 0.09897232],
       [-0.26031363],
       [ 0.29543145],
       [ 0.13329286]])

In [27]:
def simple_gradient_descent(alpha,iterations,x,y):
    m = len(x)
    b0 = 0
    b1 = 0
    for i in range(iterations):
        y_hat = b0 + b1 * x 
        b0 = b0 - alpha * 1/m * sum(y_hat - y)
        b1 = b1 - alpha * 1/m * sum((y_hat - y) * x)
    return b0, b1

In [28]:
betas = simple_gradient_descent(0.1,1000,x,y)
print(b0)
print(b1)

[13.26526936 14.30404776 14.38357936 14.26687071 13.97887145]
[15.35071518 -0.08864689 -1.03784037  1.76932922  3.85285704]
